update telemetry event endpoint
airrobe/widget-sdk-android pull request #32
Opened 2022-10-04 20:14 UTC by creative-dev-lab

### Context
telemetry event endpoint update.

### What's updated/implemented
- gradle update
- implemented `DateUtils` to get ISO format date string and used it to add an additional param called `created_at`
- updated telemetry event endpoint

### Release type
- [x] Patch
- [ ] Minor
- [ ] Major

### Peer review
- [x] The feature/changes have been peer reviewed
- [ ] Automated test coverage and correctness have been peer reviewed
- [ ] The test plan has been peer reviewed

2022-10-09 21:22 UTC, johnAirRobe requested changes

2022-10-09 21:22 UTC, johnAirRobe commented on AirRobeWidget/src/main/kotlin/com/airrobe/widgetsdk/airrobewidget/service/api_controllers/AirRobeTelemetryEventController.kt
> +                    TelemetryEventHost.Sandbox.raw + "/va",
Typo here, mean to be `v1`

2022-10-10 17:53 UTC, creative-dev-lab commented on AirRobeWidget/src/main/kotlin/com/airrobe/widgetsdk/airrobewidget/service/api_controllers/AirRobeTelemetryEventController.kt
> +                    TelemetryEventHost.Sandbox.raw + "/va",
oh yea! 😆

2022-10-12 22:08 UTC, johnAirRobe commented
Were you going to add the sdk version to this PR? Or create a new PR for it?

2022-10-12 22:27 UTC, creative-dev-lab commented
> Were you going to add the sdk version to this PR? Or create a new PR for it?

Oh, Right. almost forgot this.
I already merged the iOS one, so guess in the next PR if it's okay.

2022-10-13 05:54 UTC, johnAirRobe approved these changes

2022-10-13 14:11 UTC, merged